### ISSUE TITLE
Use standardjs

### ISSUE THREAD

**Issue by subins2000** [santhoshtr/wikivue#5]
Suggestion to use https://standardjs.com

**Comment by subins2000** [comment]
Using standard will be great cause
* No semicolons
* Single quotes
* No line column limit

Highly recommend to use it for wikivue

**Comment by santhoshtr** [comment]
I would like to stick with vue-cli tooling and its defaults so that I can upgrade the dependencies using the `vue cli upgrade`. As you can see, the project does not define any custom styling rules. It just use vue recommended styles and configuration. In general, I like to use a minimal and default recommended tooling so that we can focus on application and not tooling, formatting etc.

I am not dismissing the advantages of standardjs. I just don't consider that as an option for this project.
